### PR TITLE
Use latest version information if current major ver is unknown

### PR DESCRIPTION
**Pull request by addaleax**
Use the version information for `latest` if the current major version is not known, e.g. because it is test version of one of the io.js releases.

### CODE REVIEW

**Comment by MylesBorins** [comment]
lGtm

**Comment by Fishrock123** [comment]
This also seems to fix an issue I was having with pre-release versions of node. 👍

**Comment by cjihrig** [comment]
LGTM

**Comment by Fishrock123** [comment]
LGTM

**Pull request merged**
