### PR TITLE
[WIP] React FE

### PR DESCRIPTION
**Pull request by MarshallOfSound**
Based on the poll in #47 it looks like React is the popular option.

This is a loose WIP for reactifying the existing front end.  There are few things I still want to be their own components (like the super fancy cube spinner).

Also, this currently has 0 react tests so I'll want to bring in something like `enzyme` before this gets merged.

### CODE REVIEW

**Comment by felixrieseberg** [comment]
🎉 Looks already pretty good to me! I'm totally fine with adding more tests in a later PR. Having the front-end setup should make it easier for us to shizzle away at some interesting details.

**Review by delvedor — APPROVED** [review]
LGTM, I agree with @felixrieseberg, we can add more test later :)

**Review by gibfahn — APPROVED** [review]

**Comment by gibfahn** [comment]
Agreed, "the installer works" seems like a decent first test.

Maybe just leave a `TODO: add tests` somewhere.

**Comment by felixrieseberg** [comment]
Okay, I'll merge this puppy now just to make sure that we can all have something to work with ✌️

**Pull request merged**
