### PR TITLE
Add linter and lint files

### LINKED ISSUE #9: Add linter

### PR DESCRIPTION
**Pull request by geek**
Closes #9

### CODE REVIEW

**Comment by cjihrig** [comment]
LGTM

**Comment by Fishrock123** [comment]
I don't think we should go this route. Node core's styles are due to the git history. No reason to replicate them here. We should use `standard` or something, like the website does.

**Comment by geek** [comment]
@Fishrock123 Node.js already has a standard coding style. There is no need to deviate from the existing style within any repository under the nodejs umbrella. If there is an issue with the existing Node.js style then you need to update it in core.

**Comment by rvagg** [comment]
We don't have an established history of imposing coding styles on other repositories in the org, just see the website for an example of deviation. I've always been a fan of "whoever starts the repo gets to set the initial coding style" with that being up for discussion along the way by additional collaborators. It's pretty clear that @mikeal opted for sans-semicolons in the coding style here, deviating too dramatically from that style is needless churn.

I'm -0, basically. i.e. I don't care very much but hate churn for the sake of churn and pointless arguments over code style as if we have objective data to _prove_ that one style is better than another by an absolute metric. Bleh.

**Comment by geek** [comment]
@rvagg first and foremost, I am not a fan of the nodejs style. This PR isn't needless churn, it fixes several global variable leaks. There is also no debate about coding style with this PR, I am not removing some existing style as there is none.

At no point am I saying one style is better than another, and this PR is not churn for the sake of churn. This PR _adds_ style to the repo and fixes several bugs along the way.

Why I am having to defend a code change that fixes issues and improves quality is bizarre, to say the least.

**Comment by mikeal** [comment]
I'd be +1 on moving to [standard](https://github.com/feross/standard) style, not the Node.js Core style which is not widely adopted in the community.

**Comment by delvedor** [comment]
I agree with @mikeal, in addition Standard is the code style of Electron 😄

**Comment by geek** [comment]
@mikeal makes sense. Can we standardize all of the node repos under the node org so that they are all consistent? If not, they should have a clear style guide documented and enforced at the test level per repo. It would be nice if each repo creator is able to pick the style that they are also in charge of being the lead maintainer of the repo.

**Comment by Fishrock123** [comment]
> Can we standardize all of the node repos under the node org so that they are all consistent? 

No. Node core will always be somewhat the way it is for historical reasons.

Nothing else should follow it's style, it's silly but prevents needing impossibly large merge conflicts.

**Comment by Fishrock123** [comment]
If you have improvements that are something else than moving to node core's absurd style, please make a new PR with those or update this one.

**Comment by JoeDoyle23** [comment]
The consensus is that we want to use Standard, so closing the PR.

**Pull request closed without merging**
