### PR TITLE
Let's get this going: A foundation

### PR DESCRIPTION
**Pull request by felixrieseberg**
First of all: Apologies for the mega-PR. I noticed that we haven't really gotten far in the last two weeks and I believe one of the reasons is that there isn't enough foundation for us to build on, so I took it upon myself to get the basics in.

*I'm not trying to force any of these implementations onto the project. I believe that us having _something_ in place will make it easier to start working on the app.*

### Stuff added
* Upgraded all code to "modern JavaScript"
* Updated StandardJS, Electron, and other packages
* Added a proper build pipeline, icons, and installer configuration
* Added a basic window menu (and handlers)
* Added a process manager (developer mode only)
* Added a file-logger, allowing us to collect logs from production builds
* Added a window position and size memory feature
* Added tests (:sparkles:) with Ava, Sinon, and Mockery

cc @nodejs/electron-installer

### CODE REVIEW

**Review by delvedor — APPROVED** [review]
Awesome work! Thank you for taking it up!
If the others approve this work, I think this can be merged and the next step will be take a final decision on the front-end framework :)

**Review by MarshallOfSound — APPROVED** [review]

**Review by gibfahn — APPROVED** [review]

**Comment by Fishrock123** [comment]
yay

**Comment by refack** [comment]
@felixrieseberg so it is your PR 😋

**Comment by ljharb** [comment]
Hm, there doesn't seem to be a team. @Trott, any idea how we can make one?

**Comment by ljharb** [comment]
Hm, there doesn't seem to be a team. @Trott, any idea how we can make one?

**Comment by Trott** [comment]
@ljharb Give me a name for the team and a list of GitHub handles who should be on it and I'll make one.

**Comment by ljharb** [comment]
cc @nodejs/version-management

**Pull request merged**
